apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin
        #env:
        #- name: WORDPRESS_DB_HOST
        #  value: wordpress-mysql
        #- name: WORDPRESS_DB_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: mysql-pass
        #      key: password
        ports:
        - containerPort: 5000
          name: phpmyadmin
          # volumeMounts:
          #- name: wordpress-persistent-storage
          # mountPath: /www/localhost
          # volumes:
          # - name: wordpress-persistent-storage
          # persistentVolumeClaim:
          # claimName: wp-pv-claim
